---
- name: Run osbuild_server role
  hosts: all
  become: true
  tasks:
    - name: Run the osbuild setup_server role to configure imagebuilder host
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server
        